### ISSUE TITLE
ImcSdk-0.9.3 enforce vnic value even 'vntag_mode' is disabled

### ISSUE THREAD

**Issue by brucelok** [CiscoUcs/imcsdk#168]
After upgraded to imcsdk to 0.9.3.0, it enforcesto value input for some attributes(eg: ‘uplinkFailover’, ‘uplinkFailbackTimeout’, etc) in vnic even 'vntag_mode' is set to 'disabled'.

If you look at codes, some attributes disallowed ‘NONE’ value, eg: ‘uplinkFailover’, ‘uplinkFailbackTimeout’, ‘vmq’, ‘trusted_class_of_service’, etc
[https://github.com/CiscoUcs/imcsdk/blob/master/imcsdk/mometa/adaptor/AdaptorEthGenProfile.py](https://github.com/CiscoUcs/imcsdk/blob/master/imcsdk/mometa/adaptor/AdaptorEthGenProfile.py)
Looking at CIMC documentation, uplinkFailover and etc are only needed when VNTAG mode is enabled.

Here is the issue I tested with imcsdk 0.9.3.0.  I attempted to update the vnic's vlan id, but it kept throwing error that uplink_failover cannot be 'N/A' (no value)
```
[root@cimc3a /]# cat /etc/redhat-release
CentOS Linux release 7.4.1708 (Core)
[root@cimc3a /]# python
Python 2.7.13 (default, Jan 11 2018, 19:03:59)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-16)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>>
>>>
>>> from imcsdk import *; from imcsdk.imchandle import ImcHandle
>>> handle = ImcHandle('192.168.1.123','admin','password'); handle.login()
True
>>> print handle.query_dn('sys/rack-unit-1/adaptor-1/general')

Managed Object			:	AdaptorGenProfile
--------------
child_action                    :None
configuration_pending           :no
dn                              :sys/rack-unit-1/adaptor-1/general
fip_mode                        :Enabled
iscsi_boot_supported            :True
lldp                            :Enabled
model                           :UCSC-PCIE-CSC-02
pci_link                        :None
pci_slot                        :1
product_name                    :UCS VIC 1225
revision                        :6
rn                              :general
serial                          :FCH1905799D
status                          :None
usnic_supported                 :True
vendor                          :Cisco Systems Inc
vendor_id                       :V03
vntag_mode                      :Disabled


>>> obj = handle.query_dn('sys/rack-unit-1/adaptor-1/host-eth-eth1/general')
>>> print obj

Managed Object			:	AdaptorEthGenProfile
--------------
arfs                            :enabled
child_action                    :None
dn                              :sys/rack-unit-1/adaptor-1/host-eth-eth1/general
nvgre                           :disabled
order                           :ANY
pci_link                        :0
rate_limit                      :OFF
rn                              :general
status                          :None
trusted_class_of_service        :disabled
uplink_failback_timeout         :N/A
uplink_failover                 :N/A
vlan                            :110
vlan_mode                       :TRUNK
vmq                             :disabled
vxlan                           :disabled

>>> setattr(obj,'vlan','111')
>>> handle.set_mo(obj)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/imcsdk/imchandle.py", line 458, in set_mo
    self._commit(timeout=timeout)
  File "/usr/local/lib/python2.7/site-packages/imcsdk/imchandle.py", line 517, in _commit
    response = self.post_elem(elem, timeout=timeout)
  File "/usr/local/lib/python2.7/site-packages/imcsdk/imcsession.py", line 287, in post_elem
    response = xc.from_xml_str(response_str, self)
  File "/usr/local/lib/python2.7/site-packages/imcsdk/imcxmlcodec.py", line 91, in from_xml_str
    raise ex.ImcException(error_code, error_descr)
imcsdk.imcexception.ImcException: [ErrorCode]: ERR-xml-parse-error[ErrorDescription]: XML PARSING ERROR: Element 'adaptorEthGenProfile', attribute 'uplinkFailover': [facet 'enumeration'] The value 'N/A' is not an element of the set {'enabled', 'disabled', 'Enabled', 'Disabled'}. Element 'adaptorEthGenProfile', attribute 'uplinkFailover': 'N/A' is not a valid value of the atomic type 'enabledDisabled'.
>>>
>>> import imcsdk; imcsdk.__version__
'0.9.3.0'
>>>
```
After I downgraded to imcsdk-0.9.2.0, it is fine. it doesn't ask for those values. I could update vlan id on the vnic as an example.
```
[root@cimc3 /]# cat /etc/redhat-release
CentOS Linux release 7.4.1708 (Core)
[root@cimc3 /]# python
Python 2.7.13 (default, Jan 11 2018, 19:03:59)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-16)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import imcsdk; imcsdk.__version__
'0.9.2.0'
>>> from imcsdk import *; from imcsdk.imchandle import ImcHandle
>>> handle = ImcHandle('192.168.1.123','admin','password'); handle.login()
True
>>> print handle.query_dn('sys/rack-unit-1/adaptor-1/general')

Managed Object			:	AdaptorGenProfile
--------------
child_action                    :None
configuration_pending           :no
dn                              :sys/rack-unit-1/adaptor-1/general
fip_mode                        :Enabled
iscsi_boot_supported            :True
lldp                            :Enabled
model                           :UCSC-PCIE-CSC-02
pci_slot                        :1
product_name                    :UCS VIC 1225
revision                        :6
rn                              :general
serial                          :FCH1905799D
status                          :None
usnic_supported                 :True
vendor                          :Cisco Systems Inc
vendor_id                       :V03
vntag_mode                      :Disabled


>>> obj = handle.query_dn('sys/rack-unit-1/adaptor-1/host-eth-eth1/general')
>>> print obj

Managed Object			:	AdaptorEthGenProfile
--------------
arfs                            :enabled
child_action                    :None
dn                              :sys/rack-unit-1/adaptor-1/host-eth-eth1/general
[X]nvgre                        :disabled
order                           :ANY
[X]pciLink                      :0
rate_limit                      :OFF
rn                              :general
status                          :None
trusted_class_of_service        :disabled
uplink_failback_timeout         :N/A
uplink_failover                 :N/A
vlan                            :110
vlan_mode                       :TRUNK
vmq                             :disabled
[X]vxlan                        :disabled


>>> setattr(obj,'vlan','111')
>>> handle.set_mo(obj)
>>> print obj

Managed Object			:	AdaptorEthGenProfile
--------------
arfs                            :enabled
child_action                    :None
dn                              :sys/rack-unit-1/adaptor-1/host-eth-eth1/general
[X]nvgre                        :disabled
order                           :ANY
[X]pciLink                      :0
rate_limit                      :OFF
rn                              :general
status                          :modified
trusted_class_of_service        :disabled
uplink_failback_timeout         :N/A
uplink_failover                 :N/A
vlan                            :111
vlan_mode                       :TRUNK
vmq                             :disabled
[X]vxlan                        :disabled


>>> 
```
This issue may be probably happened on other classes which I haven't  tested

**Comment by brucelok** [comment]
@waghswapnil  just quick tested 0.9.3.1 doesn't fix the bug
workaround still downgrading to 0.9.2.0

**Comment by brucelok** [comment]
@waghswapnil  I checked the fix is available in master branch
just tested by reinstalled imcsdk from github, and verified the issue is resolved, thanks
