### ISSUE TITLE
V2 api bios_tokens_set uses non-existent sanitize_xml_parsing_error

### ISSUE THREAD

**Issue by mtimm** [CiscoUcs/imcsdk#174]
bios_token_set is not usable due to this:

```Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "imcsdk/apis/v2/server/bios.py", line 360, in bios_tokens_set
    from imcsdk.imccoreutils import load_class, sanitize_xml_parsing_error
ImportError: cannot import name sanitize_xml_parsing_error
```

**Comment by mtimm** [comment]
Resolved via https://github.com/CiscoUcs/imcsdk/commit/c8a48e36
